-- ERD v1.1: docs/development/database-erd.md (본문 3장 우선).
-- 미정: global_stats, candidates.quality, AI 실행 상태 CHECK, 운영 seed·권한/트리거 정책.
-- FK는 삭제 전파 없이 NO ACTION을 사용한다. 탈퇴/보관 정책은 후속 마이그레이션.
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    provider_user_id TEXT NOT NULL,
    nickname TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'operator')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'withdrawn')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    withdrawn_at TIMESTAMPTZ,
    UNIQUE (provider, provider_user_id)
);

CREATE TABLE user_settings (
    user_id BIGINT PRIMARY KEY,
    star_list_public BOOLEAN NOT NULL DEFAULT true,
    notification_prefs JSONB NOT NULL DEFAULT '{"achievement":true,"reopen":true,"challenge":true,"follow":false}'::jsonb,
    onboarding_done BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    target_type TEXT NOT NULL CHECK (target_type IN ('user', 'star')),
    target_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, target_type, target_id)
);

CREATE TABLE stars (
    tic_id BIGINT PRIMARY KEY,
    teff_k NUMERIC,
    radius_rsun NUMERIC,
    tmag NUMERIC,
    confirmed_count SMALLINT NOT NULL,
    service_status TEXT NOT NULL CHECK (service_status IN ('hidden', 'published'))
);

CREATE TABLE observation_datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tic_id BIGINT NOT NULL,
    sector SMALLINT NOT NULL,
    start_btjd NUMERIC NOT NULL,
    end_btjd NUMERIC NOT NULL,
    cadence TEXT NOT NULL,
    source_version TEXT NOT NULL,
    time_system TEXT NOT NULL,
    UNIQUE (tic_id, sector, source_version)
);

CREATE TABLE publication_bundles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tic_id BIGINT NOT NULL,
    bundle_version TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('staging', 'current', 'archived')),
    manifest JSONB NOT NULL,
    fold_reference_time_btjd DOUBLE PRECISION NOT NULL,
    base_days NUMERIC NOT NULL,
    published_at TIMESTAMPTZ
);

CREATE TABLE light_curve_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tic_id BIGINT NOT NULL,
    sector SMALLINT NOT NULL,
    binning_revision TEXT NOT NULL,
    start_btjd DOUBLE PRECISION NOT NULL,
    bin_minutes NUMERIC NOT NULL,
    n_points INTEGER NOT NULL,
    flux REAL[] NOT NULL,
    flux_scatter NUMERIC,
    gaps JSONB NOT NULL,
    UNIQUE (tic_id, sector, binning_revision),
    CHECK (n_points > 0 AND array_ndims(flux) = 1 AND cardinality(flux) = n_points),
    CHECK (bin_minutes > 0)
);

CREATE TABLE periodograms (
    bundle_id BIGINT PRIMARY KEY,
    period_min_days NUMERIC NOT NULL,
    period_max_days NUMERIC NOT NULL,
    n_periods INTEGER NOT NULL,
    power REAL[] NOT NULL,
    CHECK (n_periods > 0 AND array_ndims(power) = 1 AND cardinality(power) = n_periods),
    CHECK (period_min_days > 0 AND period_max_days > period_min_days)
);

CREATE TABLE candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tic_id BIGINT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'retired')),
    updated_bundle_id BIGINT NOT NULL,
    removal_step SMALLINT NOT NULL,
    period_days NUMERIC NOT NULL,
    epoch_btjd NUMERIC NOT NULL,
    duration_hours NUMERIC NOT NULL,
    depth_ppm NUMERIC NOT NULL,
    bls_power NUMERIC NOT NULL,
    transit_model JSONB NOT NULL,
    discoverable BOOLEAN NOT NULL,
    is_confirmed BOOLEAN NOT NULL
);

CREATE TABLE candidate_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    multiplier NUMERIC NOT NULL,
    alias_period_days NUMERIC NOT NULL
);

CREATE TABLE external_signal_references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT,
    source TEXT NOT NULL,
    external_id TEXT NOT NULL,
    disposition TEXT,
    period_days NUMERIC,
    fetched_on DATE NOT NULL,
    tic_id BIGINT NOT NULL,
    epoch_btjd NUMERIC
);

CREATE TABLE candidate_dispositions (
    candidate_id BIGINT PRIMARY KEY,
    disposition TEXT NOT NULL CHECK (disposition IN ('confirmed', 'fp', 'pc', 'none')),
    answer_class TEXT NOT NULL CHECK (answer_class IN ('graded', 'analysis')),
    planet_truth TEXT CHECK (planet_truth IN ('planet', 'not_planet')),
    rule_version TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL,
    source_refs JSONB NOT NULL
);

CREATE TABLE ai_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    execution_id BIGINT NOT NULL,
    score NUMERIC,
    verdict TEXT CHECK (verdict IN ('rejected', 'hold', 'approved')),
    threshold_version TEXT NOT NULL,
    raw_output JSONB
);

CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    tic_id BIGINT NOT NULL,
    bundle_id BIGINT NOT NULL,
    request_id UUID NOT NULL UNIQUE,
    submission_kind TEXT NOT NULL CHECK (submission_kind IN ('candidate', 'no_candidate', 'skipped')),
    curve_step SMALLINT NOT NULL,
    removed_candidate_ids BIGINT[] NOT NULL,
    submitted_period NUMERIC,
    matched_period NUMERIC,
    harmonic_multiplier NUMERIC,
    phase_start NUMERIC,
    phase_end NUMERIC,
    fold_reference_time_btjd DOUBLE PRECISION NOT NULL,
    epoch_btjd NUMERIC,
    duration_hours NUMERIC,
    user_judgment TEXT CHECK (user_judgment IN ('LIKELY_PLANET', 'UNLIKELY_PLANET', 'UNSURE')),
    evidence_checks JSONB NOT NULL,
    match_result TEXT NOT NULL CHECK (match_result IN ('matched', 'matched_harmonic', 'not_matched', 'duplicate', 'ambiguous_match', 'none_wrong', 'skipped')),
    matched_candidate_id BIGINT,
    achievement_result TEXT NOT NULL CHECK (achievement_result IN ('recognized', 'judgment_mismatch', 'pending_publish', 'already_recognized', 'none')),
    retry_of_submission_id BIGINT,
    answer_viewed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correction_reason TEXT,
    residual_model_version TEXT NOT NULL,
    periodogram_config_version TEXT NOT NULL,
    memo TEXT,
    rule_version TEXT NOT NULL,
    CHECK (phase_start >= 0 AND phase_start < 1 AND phase_end > phase_start AND phase_end < phase_start + 1),
    CHECK ((submission_kind = 'candidate' AND user_judgment IS NOT NULL AND submitted_period IS NOT NULL AND phase_start IS NOT NULL AND phase_end IS NOT NULL) OR (submission_kind <> 'candidate' AND user_judgment IS NULL)),
    CHECK ((match_result IN ('matched', 'matched_harmonic', 'duplicate') AND matched_candidate_id IS NOT NULL) OR (match_result NOT IN ('matched', 'matched_harmonic', 'duplicate') AND matched_candidate_id IS NULL))
);

CREATE TABLE analysis_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    tic_id BIGINT NOT NULL,
    snapshot_params JSONB NOT NULL,
    versions JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE analysis_snapshots (
    history_id BIGINT PRIMARY KEY,
    bins SMALLINT NOT NULL DEFAULT 150,
    folded_flux REAL[] NOT NULL,
    folded_err REAL[] NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (bins > 0 AND array_ndims(folded_flux) = 1 AND cardinality(folded_flux) = bins AND array_ndims(folded_err) = 1 AND cardinality(folded_err) = bins)
);

CREATE TABLE user_candidate_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    achievement_type TEXT NOT NULL CHECK (achievement_type IN ('confirmed', 'unconfirmed', 'fp')),
    recognized_submission_id BIGINT NOT NULL,
    recognized_analysis_id BIGINT,
    recognized_at TIMESTAMPTZ NOT NULL,
    relabeled_at TIMESTAMPTZ,
    relabel_disposition TEXT,
    UNIQUE (user_id, candidate_id)
);

CREATE TABLE user_star_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    tic_id BIGINT NOT NULL,
    planet_count SMALLINT NOT NULL DEFAULT 0,
    achievement_count SMALLINT NOT NULL DEFAULT 0,
    fp_success BOOLEAN NOT NULL DEFAULT false,
    progress_stage TEXT NOT NULL DEFAULT 'unexplored' CHECK (progress_stage IN ('unexplored', 'in_progress', 'completed')),
    current_curve_step SMALLINT NOT NULL DEFAULT 0,
    completion_reason TEXT CHECK (completion_reason IN ('all_found', 'undiscoverable_only', 'skipped')),
    reopen_pending BOOLEAN NOT NULL DEFAULT false,
    completed_at TIMESTAMPTZ,
    reopened_at TIMESTAMPTZ,
    UNIQUE (user_id, tic_id)
);

CREATE TABLE star_unlocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    tic_id BIGINT NOT NULL,
    unlock_reason TEXT NOT NULL CHECK (unlock_reason IN ('tutorial', 'achievement', 'challenge')),
    trigger_tic_id BIGINT,
    trigger_achievement_id BIGINT,
    seq SMALLINT,
    generation SMALLINT NOT NULL,
    angle_deg NUMERIC NOT NULL,
    radius_jitter NUMERIC NOT NULL,
    depth_z NUMERIC NOT NULL,
    unlocked_at TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id, tic_id),
    UNIQUE (trigger_achievement_id, seq),
    CHECK (unlock_reason <> 'achievement' OR (trigger_achievement_id IS NOT NULL AND seq IS NOT NULL)),
    CHECK (seq >= 0)
);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('user', 'system_thread')),
    user_id BIGINT,
    candidate_id BIGINT,
    board TEXT NOT NULL CHECK (board IN ('star', 'free')),
    tic_id BIGINT,
    tag TEXT CHECK (tag IN ('ANALYSIS', 'QUESTION', 'DISCUSSION', 'INFORMATION', 'GENERAL')),
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('visible', 'hidden', 'deleted')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((kind = 'user' AND user_id IS NOT NULL AND candidate_id IS NULL) OR (kind = 'system_thread' AND user_id IS NULL AND candidate_id IS NOT NULL AND tag IS NULL AND board = 'star')),
    CHECK ((board = 'star' AND tic_id IS NOT NULL) OR (board = 'free' AND tic_id IS NULL))
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    body TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('visible', 'hidden', 'deleted')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction TEXT NOT NULL CHECK (reaction IN ('agree', 'disagree')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (post_id, user_id)
);

CREATE TABLE published_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    history_id BIGINT NOT NULL UNIQUE,
    published_at TIMESTAMPTZ NOT NULL,
    unpublished_at TIMESTAMPTZ,
    hidden_at TIMESTAMPTZ
);

CREATE TABLE post_source_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT,
    comment_id BIGINT,
    target_type TEXT NOT NULL CHECK (target_type IN ('thread', 'analysis')),
    target_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((post_id IS NOT NULL) <> (comment_id IS NOT NULL))
);

CREATE TABLE post_history_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    history_id BIGINT NOT NULL,
    attached_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (post_id, history_id)
);

CREATE TABLE comment_history_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    history_id BIGINT NOT NULL,
    attached_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (comment_id, history_id)
);

CREATE TABLE tutorial_stars (
    seq SMALLINT PRIMARY KEY,
    tic_id BIGINT NOT NULL,
    intent TEXT NOT NULL CHECK (intent IN ('deep_confirmed', 'shallow_confirmed', 'fp', 'deep_fp', 'multi_fp')),
    active BOOLEAN NOT NULL,
    CHECK (seq BETWEEN 1 AND 5)
);

CREATE TABLE challenge_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_no INTEGER NOT NULL UNIQUE,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    target_tic_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('planned', 'active', 'closed'))
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('achievement', 'reopen', 'challenge', 'comment', 'relabel', 'follow')),
    payload JSONB NOT NULL,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stats_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date DATE NOT NULL,
    scope TEXT NOT NULL CHECK (scope IN ('global', 'round')),
    metrics JSONB NOT NULL,
    round_id BIGINT,
    CHECK ((scope = 'round') = (round_id IS NOT NULL))
);

CREATE TABLE operation_settings (
    rule_version TEXT PRIMARY KEY,
    "values" JSONB NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL,
    note TEXT NOT NULL
);

CREATE TABLE ai_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_version TEXT NOT NULL,
    checkpoint TEXT,
    status TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    error TEXT,
    duration_ms BIGINT
);

CREATE TABLE candidate_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    bundle_id BIGINT NOT NULL,
    field TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    changed_at TIMESTAMPTZ NOT NULL,
    rule_version TEXT NOT NULL,
    reason TEXT
);

-- 참조 대상 생성 후 FK 적용.
ALTER TABLE user_settings ADD CONSTRAINT fk_user_settings_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE follows ADD CONSTRAINT fk_follows_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE observation_datasets ADD CONSTRAINT fk_observation_datasets_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE publication_bundles ADD CONSTRAINT fk_publication_bundles_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE light_curve_segments ADD CONSTRAINT fk_light_curve_segments_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE periodograms ADD CONSTRAINT fk_periodograms_bundle_id FOREIGN KEY (bundle_id) REFERENCES publication_bundles(id);
ALTER TABLE candidates ADD CONSTRAINT fk_candidates_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE candidates ADD CONSTRAINT fk_candidates_updated_bundle_id FOREIGN KEY (updated_bundle_id) REFERENCES publication_bundles(id);
ALTER TABLE candidate_aliases ADD CONSTRAINT fk_candidate_aliases_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates(id);
ALTER TABLE external_signal_references ADD CONSTRAINT fk_external_signal_references_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates(id);
ALTER TABLE external_signal_references ADD CONSTRAINT fk_external_signal_references_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE candidate_dispositions ADD CONSTRAINT fk_candidate_dispositions_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates(id);
ALTER TABLE ai_evaluations ADD CONSTRAINT fk_ai_evaluations_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates(id);
ALTER TABLE ai_evaluations ADD CONSTRAINT fk_ai_evaluations_execution_id FOREIGN KEY (execution_id) REFERENCES ai_executions(id);
ALTER TABLE submissions ADD CONSTRAINT fk_submissions_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE submissions ADD CONSTRAINT fk_submissions_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE submissions ADD CONSTRAINT fk_submissions_bundle_id FOREIGN KEY (bundle_id) REFERENCES publication_bundles(id);
ALTER TABLE submissions ADD CONSTRAINT fk_submissions_matched_candidate_id FOREIGN KEY (matched_candidate_id) REFERENCES candidates(id);
ALTER TABLE submissions ADD CONSTRAINT fk_submissions_retry_of_submission_id FOREIGN KEY (retry_of_submission_id) REFERENCES submissions(id);
ALTER TABLE submissions ADD CONSTRAINT fk_submissions_rule_version FOREIGN KEY (rule_version) REFERENCES operation_settings(rule_version);
ALTER TABLE analysis_histories ADD CONSTRAINT fk_analysis_histories_submission_id FOREIGN KEY (submission_id) REFERENCES submissions(id);
ALTER TABLE analysis_histories ADD CONSTRAINT fk_analysis_histories_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE analysis_histories ADD CONSTRAINT fk_analysis_histories_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE analysis_snapshots ADD CONSTRAINT fk_analysis_snapshots_history_id FOREIGN KEY (history_id) REFERENCES analysis_histories(id);
ALTER TABLE user_candidate_achievements ADD CONSTRAINT fk_user_candidate_achievements_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE user_candidate_achievements ADD CONSTRAINT fk_user_candidate_achievements_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates(id);
ALTER TABLE user_candidate_achievements ADD CONSTRAINT fk_user_candidate_achievements_recognized_submission_id FOREIGN KEY (recognized_submission_id) REFERENCES submissions(id);
ALTER TABLE user_candidate_achievements ADD CONSTRAINT fk_user_candidate_achievements_recognized_analysis_id FOREIGN KEY (recognized_analysis_id) REFERENCES published_analyses(id);
ALTER TABLE user_star_progress ADD CONSTRAINT fk_user_star_progress_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE user_star_progress ADD CONSTRAINT fk_user_star_progress_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE star_unlocks ADD CONSTRAINT fk_star_unlocks_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE star_unlocks ADD CONSTRAINT fk_star_unlocks_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE star_unlocks ADD CONSTRAINT fk_star_unlocks_trigger_tic_id FOREIGN KEY (trigger_tic_id) REFERENCES stars(tic_id);
ALTER TABLE star_unlocks ADD CONSTRAINT fk_star_unlocks_trigger_achievement_id FOREIGN KEY (trigger_achievement_id) REFERENCES user_candidate_achievements(id);
ALTER TABLE posts ADD CONSTRAINT fk_posts_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE posts ADD CONSTRAINT fk_posts_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates(id);
ALTER TABLE posts ADD CONSTRAINT fk_posts_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE comments ADD CONSTRAINT fk_comments_post_id FOREIGN KEY (post_id) REFERENCES posts(id);
ALTER TABLE comments ADD CONSTRAINT fk_comments_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE post_reactions ADD CONSTRAINT fk_post_reactions_post_id FOREIGN KEY (post_id) REFERENCES posts(id);
ALTER TABLE post_reactions ADD CONSTRAINT fk_post_reactions_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE published_analyses ADD CONSTRAINT fk_published_analyses_post_id FOREIGN KEY (post_id) REFERENCES posts(id);
ALTER TABLE published_analyses ADD CONSTRAINT fk_published_analyses_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE published_analyses ADD CONSTRAINT fk_published_analyses_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates(id);
ALTER TABLE published_analyses ADD CONSTRAINT fk_published_analyses_history_id FOREIGN KEY (history_id) REFERENCES analysis_histories(id);
ALTER TABLE post_source_links ADD CONSTRAINT fk_post_source_links_post_id FOREIGN KEY (post_id) REFERENCES posts(id);
ALTER TABLE post_source_links ADD CONSTRAINT fk_post_source_links_comment_id FOREIGN KEY (comment_id) REFERENCES comments(id);
ALTER TABLE post_history_attachments ADD CONSTRAINT fk_post_history_attachments_post_id FOREIGN KEY (post_id) REFERENCES posts(id);
ALTER TABLE post_history_attachments ADD CONSTRAINT fk_post_history_attachments_history_id FOREIGN KEY (history_id) REFERENCES analysis_histories(id);
ALTER TABLE comment_history_attachments ADD CONSTRAINT fk_comment_history_attachments_comment_id FOREIGN KEY (comment_id) REFERENCES comments(id);
ALTER TABLE comment_history_attachments ADD CONSTRAINT fk_comment_history_attachments_history_id FOREIGN KEY (history_id) REFERENCES analysis_histories(id);
ALTER TABLE tutorial_stars ADD CONSTRAINT fk_tutorial_stars_tic_id FOREIGN KEY (tic_id) REFERENCES stars(tic_id);
ALTER TABLE challenge_rounds ADD CONSTRAINT fk_challenge_rounds_target_tic_id FOREIGN KEY (target_tic_id) REFERENCES stars(tic_id);
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE stats_snapshots ADD CONSTRAINT fk_stats_snapshots_round_id FOREIGN KEY (round_id) REFERENCES challenge_rounds(id);
ALTER TABLE candidate_status_history ADD CONSTRAINT fk_candidate_status_history_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates(id);
ALTER TABLE candidate_status_history ADD CONSTRAINT fk_candidate_status_history_bundle_id FOREIGN KEY (bundle_id) REFERENCES publication_bundles(id);

CREATE UNIQUE INDEX uq_users_nickname_lower ON users (lower(nickname));
CREATE UNIQUE INDEX uq_publication_bundles_current ON publication_bundles (tic_id) WHERE status = 'current';
CREATE UNIQUE INDEX uq_posts_system_candidate ON posts (candidate_id) WHERE kind = 'system_thread';
CREATE INDEX ix_submissions_user_tic_created ON submissions (user_id, tic_id, created_at DESC);
CREATE INDEX ix_submissions_candidate_user_created ON submissions (matched_candidate_id, user_id, created_at);
CREATE INDEX ix_posts_tic_kind_created ON posts (tic_id, kind, created_at DESC);
CREATE INDEX ix_comments_post_created ON comments (post_id, created_at);
CREATE INDEX ix_posts_user_created ON posts (user_id, created_at DESC);
CREATE INDEX ix_posts_title_trgm ON posts USING GIN (title public.gin_trgm_ops);
CREATE INDEX ix_posts_body_trgm ON posts USING GIN (body public.gin_trgm_ops);
CREATE INDEX ix_published_analyses_candidate_user_published ON published_analyses (candidate_id, user_id, published_at DESC);
CREATE INDEX ix_notifications_user_read_created ON notifications (user_id, read_at, created_at DESC);

COMMENT ON COLUMN users.id IS '고유 번호';
COMMENT ON COLUMN users.provider IS '로그인 제공자 · ssafy/google';
COMMENT ON COLUMN users.provider_user_id IS '제공자 쪽 회원 ID';
COMMENT ON COLUMN users.nickname IS '닉네임(상시 변경)';
COMMENT ON COLUMN users.role IS 'member/operator';
COMMENT ON COLUMN users.status IS 'active/withdrawn';
COMMENT ON COLUMN users.created_at IS '생성 시각';
COMMENT ON COLUMN users.withdrawn_at IS '탈퇴 시각';
COMMENT ON COLUMN user_settings.user_id IS '회원';
COMMENT ON COLUMN user_settings.star_list_public IS '내 별 목록 공개';
COMMENT ON COLUMN user_settings.notification_prefs IS '알림 종류별 설정';
COMMENT ON COLUMN user_settings.onboarding_done IS '첫 방문 안내 완료';
COMMENT ON COLUMN follows.id IS '고유 번호';
COMMENT ON COLUMN follows.user_id IS '팔로우한 회원';
COMMENT ON COLUMN follows.target_type IS 'user/star';
COMMENT ON COLUMN follows.target_id IS '대상 회원 또는 별';
COMMENT ON COLUMN follows.created_at IS '생성 시각';
COMMENT ON COLUMN stars.tic_id IS '별(TIC)';
COMMENT ON COLUMN stars.teff_k IS '표면 온도(K)';
COMMENT ON COLUMN stars.radius_rsun IS '반지름(태양=1)';
COMMENT ON COLUMN stars.tmag IS 'TESS 밝기 등급';
COMMENT ON COLUMN stars.confirmed_count IS '후보표의 확정 행성 수';
COMMENT ON COLUMN stars.service_status IS 'hidden/published';
COMMENT ON COLUMN observation_datasets.id IS '고유 번호';
COMMENT ON COLUMN observation_datasets.tic_id IS '별';
COMMENT ON COLUMN observation_datasets.sector IS '섹터';
COMMENT ON COLUMN observation_datasets.start_btjd IS '시작(BTJD)';
COMMENT ON COLUMN observation_datasets.end_btjd IS '끝(BTJD)';
COMMENT ON COLUMN observation_datasets.cadence IS '촬영 간격';
COMMENT ON COLUMN observation_datasets.source_version IS '원천 버전';
COMMENT ON COLUMN observation_datasets.time_system IS '시간 체계';
COMMENT ON COLUMN publication_bundles.id IS '고유 번호';
COMMENT ON COLUMN publication_bundles.tic_id IS '별';
COMMENT ON COLUMN publication_bundles.bundle_version IS '판 버전';
COMMENT ON COLUMN publication_bundles.status IS 'staging/current/archived';
COMMENT ON COLUMN publication_bundles.manifest IS '세그먼트 id 집합·checksum·계산 버전·격자 규칙';
COMMENT ON COLUMN publication_bundles.fold_reference_time_btjd IS '위상 접기 기준 시각';
COMMENT ON COLUMN publication_bundles.base_days IS '관측 기간(일)';
COMMENT ON COLUMN publication_bundles.published_at IS '공개 시각';
COMMENT ON COLUMN light_curve_segments.id IS '고유 번호';
COMMENT ON COLUMN light_curve_segments.tic_id IS '별';
COMMENT ON COLUMN light_curve_segments.sector IS '섹터';
COMMENT ON COLUMN light_curve_segments.binning_revision IS '원천·전처리·비닝 설정 버전';
COMMENT ON COLUMN light_curve_segments.start_btjd IS '첫 점 시각';
COMMENT ON COLUMN light_curve_segments.bin_minutes IS '비닝 간격(분)';
COMMENT ON COLUMN light_curve_segments.n_points IS '점 수';
COMMENT ON COLUMN light_curve_segments.flux IS '정규화 밝기 배열';
COMMENT ON COLUMN light_curve_segments.flux_scatter IS '점간 산포(오차 대표값)';
COMMENT ON COLUMN light_curve_segments.gaps IS '빈 구간 인덱스';
COMMENT ON COLUMN periodograms.bundle_id IS '공개 데이터 판';
COMMENT ON COLUMN periodograms.period_min_days IS '주기 축 시작';
COMMENT ON COLUMN periodograms.period_max_days IS '주기 축 끝';
COMMENT ON COLUMN periodograms.n_periods IS '격자 점 수';
COMMENT ON COLUMN periodograms.power IS '세기 배열';
COMMENT ON COLUMN candidates.id IS '고유 번호 · 판이 바뀌어도 유지';
COMMENT ON COLUMN candidates.tic_id IS '별';
COMMENT ON COLUMN candidates.status IS 'active/retired';
COMMENT ON COLUMN candidates.updated_bundle_id IS '마지막 갱신 판';
COMMENT ON COLUMN candidates.removal_step IS '배치 제거 순번';
COMMENT ON COLUMN candidates.period_days IS '주기(일)';
COMMENT ON COLUMN candidates.epoch_btjd IS '중심 시각';
COMMENT ON COLUMN candidates.duration_hours IS '지속시간';
COMMENT ON COLUMN candidates.depth_ppm IS '깊이';
COMMENT ON COLUMN candidates.bls_power IS 'BLS 세기';
COMMENT ON COLUMN candidates.transit_model IS '통과 모델 파라미터';
COMMENT ON COLUMN candidates.discoverable IS '현재 데이터로 찾을 수 있는지';
COMMENT ON COLUMN candidates.is_confirmed IS '외부 확정 여부';
COMMENT ON COLUMN candidate_aliases.id IS '고유 번호';
COMMENT ON COLUMN candidate_aliases.candidate_id IS '후보';
COMMENT ON COLUMN candidate_aliases.multiplier IS '배수';
COMMENT ON COLUMN candidate_aliases.alias_period_days IS '별칭 주기';
COMMENT ON COLUMN external_signal_references.id IS '고유 번호';
COMMENT ON COLUMN external_signal_references.candidate_id IS '후보(NULL 가능)';
COMMENT ON COLUMN external_signal_references.source IS 'tce/toi/archive/exofop';
COMMENT ON COLUMN external_signal_references.external_id IS '원천 ID';
COMMENT ON COLUMN external_signal_references.disposition IS '원천 판정';
COMMENT ON COLUMN external_signal_references.period_days IS '주기';
COMMENT ON COLUMN external_signal_references.fetched_on IS '조회일';
COMMENT ON COLUMN external_signal_references.tic_id IS '별';
COMMENT ON COLUMN external_signal_references.epoch_btjd IS '외부 신호 중심 시각';
COMMENT ON COLUMN candidate_dispositions.candidate_id IS '후보';
COMMENT ON COLUMN candidate_dispositions.disposition IS 'confirmed/fp/pc/none';
COMMENT ON COLUMN candidate_dispositions.answer_class IS 'graded/analysis';
COMMENT ON COLUMN candidate_dispositions.planet_truth IS 'planet/not_planet/null';
COMMENT ON COLUMN candidate_dispositions.rule_version IS '규칙 버전';
COMMENT ON COLUMN candidate_dispositions.applied_at IS '적용 시각';
COMMENT ON COLUMN candidate_dispositions.source_refs IS '분류 원천';
COMMENT ON COLUMN ai_evaluations.id IS '고유 번호';
COMMENT ON COLUMN ai_evaluations.candidate_id IS '후보';
COMMENT ON COLUMN ai_evaluations.execution_id IS '실행';
COMMENT ON COLUMN ai_evaluations.score IS '점수';
COMMENT ON COLUMN ai_evaluations.verdict IS 'rejected/hold/approved';
COMMENT ON COLUMN ai_evaluations.threshold_version IS '임계값 버전';
COMMENT ON COLUMN ai_evaluations.raw_output IS '모델 원본 출력';
COMMENT ON COLUMN submissions.id IS '고유 번호 · 동률 순서';
COMMENT ON COLUMN submissions.user_id IS '회원';
COMMENT ON COLUMN submissions.tic_id IS '별';
COMMENT ON COLUMN submissions.bundle_id IS '판정 당시 판';
COMMENT ON COLUMN submissions.request_id IS '멱등 요청 ID';
COMMENT ON COLUMN submissions.submission_kind IS 'candidate/no_candidate/skipped';
COMMENT ON COLUMN submissions.curve_step IS '곡선 단계';
COMMENT ON COLUMN submissions.removed_candidate_ids IS '뺀 후보(정렬)';
COMMENT ON COLUMN submissions.submitted_period IS '제출 주기';
COMMENT ON COLUMN submissions.matched_period IS '정정 대표 주기';
COMMENT ON COLUMN submissions.harmonic_multiplier IS '배율';
COMMENT ON COLUMN submissions.phase_start IS '위상 시작';
COMMENT ON COLUMN submissions.phase_end IS '위상 끝';
COMMENT ON COLUMN submissions.fold_reference_time_btjd IS '그때 기준 시각';
COMMENT ON COLUMN submissions.epoch_btjd IS '서버 파생 epoch';
COMMENT ON COLUMN submissions.duration_hours IS '서버 파생 지속시간';
COMMENT ON COLUMN submissions.user_judgment IS 'LIKELY/UNLIKELY/UNSURE';
COMMENT ON COLUMN submissions.evidence_checks IS '근거 3종';
COMMENT ON COLUMN submissions.match_result IS '판정 결과';
COMMENT ON COLUMN submissions.matched_candidate_id IS '일치 후보';
COMMENT ON COLUMN submissions.achievement_result IS '성과 결과';
COMMENT ON COLUMN submissions.retry_of_submission_id IS '재도전 원 제출';
COMMENT ON COLUMN submissions.answer_viewed IS '상세 열람';
COMMENT ON COLUMN submissions.created_at IS '접수 시각';
COMMENT ON COLUMN submissions.correction_reason IS '정정 사유';
COMMENT ON COLUMN submissions.residual_model_version IS '잔차 모델 버전';
COMMENT ON COLUMN submissions.periodogram_config_version IS '주기도 설정 버전';
COMMENT ON COLUMN submissions.memo IS '분석 메모';
COMMENT ON COLUMN submissions.rule_version IS '판정 규칙 버전';
COMMENT ON COLUMN analysis_histories.id IS '고유 번호';
COMMENT ON COLUMN analysis_histories.submission_id IS '제출';
COMMENT ON COLUMN analysis_histories.user_id IS '회원';
COMMENT ON COLUMN analysis_histories.tic_id IS '별';
COMMENT ON COLUMN analysis_histories.snapshot_params IS '재현 파라미터';
COMMENT ON COLUMN analysis_histories.versions IS '데이터·계산 버전';
COMMENT ON COLUMN analysis_histories.created_at IS '생성 시각';
COMMENT ON COLUMN analysis_snapshots.history_id IS '히스토리';
COMMENT ON COLUMN analysis_snapshots.bins IS '구간 수(150)';
COMMENT ON COLUMN analysis_snapshots.folded_flux IS '구간별 밝기 중앙값';
COMMENT ON COLUMN analysis_snapshots.folded_err IS '구간별 오차';
COMMENT ON COLUMN analysis_snapshots.created_at IS '생성 시각';
COMMENT ON COLUMN user_candidate_achievements.id IS '고유 번호';
COMMENT ON COLUMN user_candidate_achievements.user_id IS '회원';
COMMENT ON COLUMN user_candidate_achievements.candidate_id IS '후보';
COMMENT ON COLUMN user_candidate_achievements.achievement_type IS 'confirmed/unconfirmed/fp';
COMMENT ON COLUMN user_candidate_achievements.recognized_submission_id IS '근거 제출';
COMMENT ON COLUMN user_candidate_achievements.recognized_analysis_id IS '근거 공개 분석(미확정)';
COMMENT ON COLUMN user_candidate_achievements.recognized_at IS '인정 시각';
COMMENT ON COLUMN user_candidate_achievements.relabeled_at IS '라벨 갱신 표식';
COMMENT ON COLUMN user_candidate_achievements.relabel_disposition IS '라벨 갱신 표식';
COMMENT ON COLUMN user_star_progress.id IS '고유 번호';
COMMENT ON COLUMN user_star_progress.user_id IS '회원';
COMMENT ON COLUMN user_star_progress.tic_id IS '별';
COMMENT ON COLUMN user_star_progress.planet_count IS '찾은 행성 수(색·궤도)';
COMMENT ON COLUMN user_star_progress.achievement_count IS '성과 수(등급 문자)';
COMMENT ON COLUMN user_star_progress.fp_success IS 'FP 판단 성공 있음';
COMMENT ON COLUMN user_star_progress.progress_stage IS 'unexplored/in_progress/completed';
COMMENT ON COLUMN user_star_progress.current_curve_step IS '현재 곡선 단계';
COMMENT ON COLUMN user_star_progress.completion_reason IS 'all_found/undiscoverable_only/skipped';
COMMENT ON COLUMN user_star_progress.reopen_pending IS '재개 대기';
COMMENT ON COLUMN user_star_progress.completed_at IS '완료 시각';
COMMENT ON COLUMN user_star_progress.reopened_at IS '재개 시각';
COMMENT ON COLUMN star_unlocks.id IS '고유 번호';
COMMENT ON COLUMN star_unlocks.user_id IS '회원';
COMMENT ON COLUMN star_unlocks.tic_id IS '별';
COMMENT ON COLUMN star_unlocks.unlock_reason IS 'tutorial/achievement/challenge';
COMMENT ON COLUMN star_unlocks.trigger_tic_id IS '발견을 일으킨 별';
COMMENT ON COLUMN star_unlocks.trigger_achievement_id IS '원인 성과';
COMMENT ON COLUMN star_unlocks.seq IS '한 성과가 연 별 중 순번';
COMMENT ON COLUMN star_unlocks.generation IS '세대';
COMMENT ON COLUMN star_unlocks.angle_deg IS '각도';
COMMENT ON COLUMN star_unlocks.radius_jitter IS '반지름 지터';
COMMENT ON COLUMN star_unlocks.depth_z IS '깊이';
COMMENT ON COLUMN star_unlocks.unlocked_at IS '발견 시각';
COMMENT ON COLUMN posts.id IS '고유 번호';
COMMENT ON COLUMN posts.kind IS 'user/system_thread';
COMMENT ON COLUMN posts.user_id IS '작성자(system_thread는 NULL)';
COMMENT ON COLUMN posts.candidate_id IS '공식 스레드의 신호';
COMMENT ON COLUMN posts.board IS 'star/free';
COMMENT ON COLUMN posts.tic_id IS '별(free는 NULL)';
COMMENT ON COLUMN posts.tag IS '대표 태그';
COMMENT ON COLUMN posts.title IS '제목';
COMMENT ON COLUMN posts.body IS '본문';
COMMENT ON COLUMN posts.status IS 'visible/hidden/deleted';
COMMENT ON COLUMN posts.created_at IS '생성 시각';
COMMENT ON COLUMN posts.updated_at IS '수정 시각';
COMMENT ON COLUMN comments.id IS '고유 번호';
COMMENT ON COLUMN comments.post_id IS '원글·스레드';
COMMENT ON COLUMN comments.user_id IS '회원';
COMMENT ON COLUMN comments.body IS '본문';
COMMENT ON COLUMN comments.status IS 'visible/hidden/deleted';
COMMENT ON COLUMN comments.created_at IS '생성 시각';
COMMENT ON COLUMN comments.updated_at IS '수정 시각';
COMMENT ON COLUMN post_reactions.id IS '고유 번호';
COMMENT ON COLUMN post_reactions.post_id IS '일반 글만';
COMMENT ON COLUMN post_reactions.user_id IS '회원';
COMMENT ON COLUMN post_reactions.reaction IS 'agree/disagree';
COMMENT ON COLUMN post_reactions.updated_at IS '수정 시각';
COMMENT ON COLUMN published_analyses.id IS '고유 번호';
COMMENT ON COLUMN published_analyses.post_id IS '공식 스레드';
COMMENT ON COLUMN published_analyses.user_id IS '작성자';
COMMENT ON COLUMN published_analyses.candidate_id IS '신호';
COMMENT ON COLUMN published_analyses.history_id IS '본인 히스토리';
COMMENT ON COLUMN published_analyses.published_at IS '공개 시각';
COMMENT ON COLUMN published_analyses.unpublished_at IS '본인 취소';
COMMENT ON COLUMN published_analyses.hidden_at IS '운영 숨김(DB 설정)';
COMMENT ON COLUMN post_source_links.id IS '고유 번호';
COMMENT ON COLUMN post_source_links.post_id IS '글(둘 중 하나)';
COMMENT ON COLUMN post_source_links.comment_id IS '답글(둘 중 하나)';
COMMENT ON COLUMN post_source_links.target_type IS 'thread/analysis';
COMMENT ON COLUMN post_source_links.target_id IS '대상 ID';
COMMENT ON COLUMN post_source_links.created_at IS '생성 시각';
COMMENT ON COLUMN post_history_attachments.id IS '고유 번호';
COMMENT ON COLUMN post_history_attachments.post_id IS '글';
COMMENT ON COLUMN post_history_attachments.history_id IS '히스토리';
COMMENT ON COLUMN post_history_attachments.attached_at IS '첨부 시각';
COMMENT ON COLUMN comment_history_attachments.id IS '고유 번호';
COMMENT ON COLUMN comment_history_attachments.comment_id IS '답글';
COMMENT ON COLUMN comment_history_attachments.history_id IS '히스토리';
COMMENT ON COLUMN comment_history_attachments.attached_at IS '첨부 시각';
COMMENT ON COLUMN tutorial_stars.seq IS '순번 1~5';
COMMENT ON COLUMN tutorial_stars.tic_id IS '별';
COMMENT ON COLUMN tutorial_stars.intent IS 'deep_confirmed/shallow_confirmed/fp/deep_fp/multi_fp';
COMMENT ON COLUMN tutorial_stars.active IS '사용 중';
COMMENT ON COLUMN challenge_rounds.id IS '고유 번호';
COMMENT ON COLUMN challenge_rounds.round_no IS '회차';
COMMENT ON COLUMN challenge_rounds.starts_on IS '시작일';
COMMENT ON COLUMN challenge_rounds.ends_on IS '종료일';
COMMENT ON COLUMN challenge_rounds.target_tic_id IS '대상 별';
COMMENT ON COLUMN challenge_rounds.description IS '한 줄 설명';
COMMENT ON COLUMN challenge_rounds.status IS 'planned/active/closed';
COMMENT ON COLUMN notifications.id IS '고유 번호';
COMMENT ON COLUMN notifications.user_id IS '회원';
COMMENT ON COLUMN notifications.type IS '종류';
COMMENT ON COLUMN notifications.payload IS '내용';
COMMENT ON COLUMN notifications.read_at IS '읽은 시각';
COMMENT ON COLUMN notifications.created_at IS '생성 시각';
COMMENT ON COLUMN stats_snapshots.id IS '고유 번호';
COMMENT ON COLUMN stats_snapshots.snapshot_date IS '집계일';
COMMENT ON COLUMN stats_snapshots.scope IS 'global/round';
COMMENT ON COLUMN stats_snapshots.metrics IS '지표';
COMMENT ON COLUMN stats_snapshots.round_id IS '회차';
COMMENT ON COLUMN operation_settings.rule_version IS '규칙 버전';
COMMENT ON COLUMN operation_settings."values" IS '설정 값 묶음';
COMMENT ON COLUMN operation_settings.applied_at IS '적용 시각';
COMMENT ON COLUMN operation_settings.note IS '변경 사유';
COMMENT ON COLUMN ai_executions.id IS '고유 번호';
COMMENT ON COLUMN ai_executions.model_version IS '모델 버전';
COMMENT ON COLUMN ai_executions.checkpoint IS '체크포인트';
COMMENT ON COLUMN ai_executions.status IS '상태';
COMMENT ON COLUMN ai_executions.started_at IS '시작';
COMMENT ON COLUMN ai_executions.error IS '실패 내용';
COMMENT ON COLUMN ai_executions.duration_ms IS '실행 시간';
COMMENT ON COLUMN candidate_status_history.id IS '고유 번호';
COMMENT ON COLUMN candidate_status_history.candidate_id IS '후보';
COMMENT ON COLUMN candidate_status_history.bundle_id IS '판';
COMMENT ON COLUMN candidate_status_history.field IS '항목';
COMMENT ON COLUMN candidate_status_history.old_value IS '이전';
COMMENT ON COLUMN candidate_status_history.new_value IS '이후';
COMMENT ON COLUMN candidate_status_history.changed_at IS '변경 시각';
COMMENT ON COLUMN candidate_status_history.rule_version IS '규칙 버전';
COMMENT ON COLUMN candidate_status_history.reason IS '변경 사유';

