-- 사건 원본과 알림함 발행을 구분한다 [S15P21C206-175]. 기존 행은 승인된 비소급 전환으로 보존한다.
ALTER TABLE notifications
    ADD COLUMN event_key TEXT,
    ADD COLUMN published_at TIMESTAMPTZ,
    ADD COLUMN publication_seq BIGINT,
    ADD CONSTRAINT ck_notification_publication CHECK (
        (event_key IS NOT NULL AND published_at IS NOT NULL AND publication_seq IS NOT NULL AND publication_seq > 0)
        OR (event_key IS NULL AND published_at IS NULL AND publication_seq IS NULL)),
    ADD CONSTRAINT uq_notification_event UNIQUE (user_id, event_key),
    ADD CONSTRAINT uq_notification_publication UNIQUE (user_id, publication_seq);

ALTER TABLE user_settings ADD COLUMN notification_epochs JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE user_settings ALTER COLUMN notification_prefs SET DEFAULT
    '{"achievement":true,"reopen":true,"challenge":true,"follow":true,"comment":true,"relabel":true}'::jsonb;
-- 오른쪽의 기존 값을 우선하므로 명시적인 false와 미지 키를 덮어쓰지 않는다.
UPDATE user_settings SET notification_prefs =
    '{"achievement":true,"reopen":true,"challenge":true,"follow":true,"comment":true,"relabel":true}'::jsonb
    || notification_prefs;

CREATE INDEX ix_notification_inbox ON notifications(user_id, published_at DESC, id DESC)
    WHERE published_at IS NOT NULL;

-- 수신자 FK를 두지 않는다. 작성자 잠금 안에서 수신자 KEY SHARE를 잡으면 상호 작성이 교착한다.
-- 실제 알림 FK는 수신자 잠금·active 확인 뒤 notifications INSERT에서 검사한다.
CREATE TABLE notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key TEXT NOT NULL,
    user_id BIGINT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('achievement','reopen','challenge','comment','relabel','follow')),
    payload JSONB NOT NULL,
    preference_epoch BIGINT NOT NULL,
    follow_id BIGINT,
    source_notification_id BIGINT,
    state TEXT NOT NULL CHECK (state IN ('pending','delivered','excluded')),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    UNIQUE(user_id, event_key)
);
CREATE INDEX ix_notification_outbox_pending ON notification_outbox(user_id, id) WHERE state='pending';

DO $$ BEGIN
    EXECUTE format('GRANT UPDATE (read_at, event_key, published_at, publication_seq) ON %I.notifications TO planetory_app', current_schema());
    EXECUTE format('GRANT SELECT, INSERT ON %I.notification_outbox TO planetory_app', current_schema());
    EXECUTE format('GRANT UPDATE (state) ON %I.notification_outbox TO planetory_app', current_schema());
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %I.notification_outbox_id_seq TO planetory_app', current_schema());
END $$;

COMMENT ON COLUMN notifications.event_key IS '생산 트랜잭션의 불변 원인 키; 기존 사건은 NULL로 보존';
COMMENT ON COLUMN notifications.published_at IS '최초 발행 시각; 알림함 90일 기준';
COMMENT ON COLUMN notifications.publication_seq IS '회원 잠금 안에서 할당하는 발행 순번; 모두 읽음 경계';
COMMENT ON COLUMN user_settings.notification_epochs IS '종류별 OFF 전환 횟수; 대기 사건이 ON 후 부활하지 않도록 보존';
COMMENT ON TABLE notification_outbox IS '작성 트랜잭션의 알림 수신 의도·당시 설정·관계와 영구 제외/발행 상태';

-- 운영자의 기존 회차 전환과 당시 수신자 확정을 원자적으로 묶는다. 기존 회차는 소급하지 않는다.
ALTER TABLE challenge_rounds ADD COLUMN notification_started_at TIMESTAMPTZ;
UPDATE challenge_rounds SET notification_started_at='-infinity'::timestamptz WHERE status<>'planned';
CREATE FUNCTION capture_challenge_notification() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='UPDATE' THEN NEW.notification_started_at := OLD.notification_started_at;
    ELSE NEW.notification_started_at := NULL;
    END IF;
    IF NEW.status='active' AND NEW.notification_started_at IS NULL THEN
        NEW.notification_started_at := clock_timestamp();
        INSERT INTO notification_outbox(event_key,user_id,type,payload,preference_epoch,state)
        SELECT 'challenge:'||NEW.id,u.id,'challenge',
               jsonb_build_object('roundId',NEW.id::text,'startedAt',NEW.notification_started_at),
               coalesce((s.notification_epochs->>'challenge')::bigint,0),
               CASE WHEN coalesce((s.notification_prefs->>'challenge')::boolean,true) THEN 'pending' ELSE 'excluded' END
          FROM users u LEFT JOIN user_settings s ON s.user_id=u.id
         -- HOME-06/POL-24: 활성 튜토리얼 5개 완료. Java TUTORIAL_STAR_COUNT와 함께 변경한다.
         -- 활성 개수로 나누면 0개/4개 설정에서도 자격을 주므로 여기만 동적으로 바꾸지 않는다.
         WHERE u.status='active' AND (SELECT count(*) FROM tutorial_stars t
                 JOIN user_star_progress p ON p.tic_id=t.tic_id
                 WHERE t.active AND p.user_id=u.id AND (p.progress_stage='completed' OR p.completed_at IS NOT NULL))=5
        ON CONFLICT(user_id,event_key) DO NOTHING;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER challenge_notification_start BEFORE INSERT OR UPDATE ON challenge_rounds
FOR EACH ROW EXECUTE FUNCTION capture_challenge_notification();
COMMENT ON COLUMN challenge_rounds.notification_started_at IS '최초 시작 알림 경계; 기존 active/closed는 -infinity로 비소급 표시';

ALTER TABLE notification_outbox ADD COLUMN follow_epoch BIGINT;
CREATE TABLE notification_events (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_key TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('reopen','relabel')),
    payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE notification_signal_state (
    candidate_id BIGINT PRIMARY KEY REFERENCES candidates(id) ON DELETE CASCADE,
    disposition TEXT,
    ai_verdict TEXT
);
-- 도입 전 상태는 비교 기준으로만 보존하며 사건으로 만들지 않는다.
INSERT INTO notification_signal_state
SELECT c.id,d.disposition,a.verdict FROM candidates c
LEFT JOIN candidate_dispositions d ON d.candidate_id=c.id
LEFT JOIN LATERAL (SELECT CASE WHEN x.status='success' THEN e.verdict END AS verdict FROM ai_evaluations e JOIN ai_executions x ON x.id=e.execution_id
 WHERE e.candidate_id=c.id
 ORDER BY x.started_at DESC,e.id DESC LIMIT 1) a ON true;
CREATE TABLE notification_candidate_changes (
    bundle_id BIGINT NOT NULL REFERENCES publication_bundles(id),
    candidate_id BIGINT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
    was_discoverable BOOLEAN NOT NULL,
    is_discoverable BOOLEAN NOT NULL,
    PRIMARY KEY(bundle_id,candidate_id)
);
-- 보존·정리 정책은 S15P21C206-258에서 확정한다. 알림함 90일은 원천/중복 근거의 삭제 TTL이 아니다.
-- archived 계산 캐시와 구분하며 재게시·재처리·pending 참조를 확인하기 전 자동 삭제하지 않는다.

-- 승인된 예외: Gold 역할에 회원 SELECT를 부여하지 않고 고정된 트리거 경로만 수신 의도를 쓴다.
CREATE FUNCTION notification_candidate_change() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    INSERT INTO notification_candidate_changes VALUES(NEW.updated_bundle_id,NEW.id,
      CASE WHEN TG_OP='INSERT' THEN false ELSE OLD.status='active' AND OLD.discoverable END,
      NEW.status='active' AND NEW.discoverable)
    ON CONFLICT(bundle_id,candidate_id) DO UPDATE SET is_discoverable=EXCLUDED.is_discoverable;
    RETURN NULL;
END $$;
CREATE TRIGGER notification_candidate_change AFTER INSERT OR UPDATE ON candidates
FOR EACH ROW EXECUTE FUNCTION notification_candidate_change();

CREATE FUNCTION notification_bundle_published() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE event_id BIGINT; signal_id BIGINT;
BEGIN
    IF NEW.status<>'current' OR (TG_OP='UPDATE' AND OLD.status='current')
       OR NOT EXISTS(SELECT 1 FROM publication_bundles WHERE id=NEW.id AND status='current')
    THEN RETURN NULL; END IF;
    FOR signal_id IN SELECT id FROM candidates WHERE updated_bundle_id=NEW.id ORDER BY id LOOP
      PERFORM notification_signal_changed(signal_id);
    END LOOP;
    IF NOT EXISTS(SELECT 1 FROM notification_candidate_changes WHERE bundle_id=NEW.id AND NOT was_discoverable AND is_discoverable) THEN RETURN NULL; END IF;
    INSERT INTO notification_events(event_key,type,payload)
    VALUES('reopen:'||NEW.tic_id||':'||NEW.id,'reopen',jsonb_build_object('ticId',NEW.tic_id::text,'bundleId',NEW.id::text))
    ON CONFLICT(event_key) DO NOTHING RETURNING id INTO event_id;
    IF event_id IS NULL THEN RETURN NULL; END IF;
    INSERT INTO notification_outbox(event_key,user_id,type,payload,preference_epoch,follow_id,follow_epoch,state)
    SELECT 'reopen:'||NEW.tic_id||':'||NEW.id,u.id,'reopen',
      jsonb_build_object('ticId',NEW.tic_id::text,'originBundleId',NEW.id::text,'targetKind','STAR_BOARD','eventId',event_id::text),
      coalesce((s.notification_epochs->>'reopen')::bigint,0),f.id,coalesce((s.notification_epochs->>'follow')::bigint,0),
      CASE WHEN coalesce((s.notification_prefs->>'reopen')::boolean,true) AND coalesce((s.notification_prefs->>'follow')::boolean,true)
      THEN 'pending' ELSE 'excluded' END
    FROM follows f JOIN users u ON u.id=f.user_id AND u.status='active'
    LEFT JOIN user_settings s ON s.user_id=u.id WHERE f.target_type='star' AND f.target_id=NEW.tic_id
    ON CONFLICT(user_id,event_key) DO NOTHING;
    RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER notification_bundle_published AFTER INSERT OR UPDATE ON publication_bundles
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION notification_bundle_published();

CREATE FUNCTION notification_signal_changed(candidate BIGINT) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE before_row notification_signal_state%ROWTYPE; next_disposition TEXT; next_ai TEXT;
        signal_tic BIGINT; axis TEXT; old_value TEXT; new_value TEXT; event_id BIGINT; cause TEXT;
BEGIN
    SELECT c.tic_id INTO signal_tic FROM candidates c JOIN publication_bundles b ON b.id=c.updated_bundle_id WHERE c.id=candidate AND b.status='current';
    IF NOT FOUND THEN RETURN; END IF;
    INSERT INTO notification_signal_state(candidate_id) VALUES(candidate) ON CONFLICT DO NOTHING;
    SELECT * INTO before_row FROM notification_signal_state WHERE candidate_id=candidate FOR UPDATE;
    SELECT disposition INTO next_disposition FROM candidate_dispositions WHERE candidate_id=candidate;
    SELECT CASE WHEN x.status='success' THEN e.verdict END INTO next_ai FROM ai_evaluations e JOIN ai_executions x ON x.id=e.execution_id
      WHERE e.candidate_id=candidate
      ORDER BY x.started_at DESC,e.id DESC LIMIT 1;
    FOREACH axis IN ARRAY ARRAY['disposition','ai_verdict'] LOOP
      old_value := CASE WHEN axis='disposition' THEN before_row.disposition ELSE before_row.ai_verdict END;
      new_value := CASE WHEN axis='disposition' THEN next_disposition ELSE next_ai END;
      -- 최초 유효 값은 비교 기준이다. 누락·실패는 판정 변경이 아니다.
      IF old_value IS NOT NULL AND new_value IS NOT NULL AND old_value<>new_value THEN
        cause := 'relabel:'||candidate||':'||axis||':'||pg_current_xact_id()::text;
        INSERT INTO notification_events(event_key,type,payload)
        VALUES(cause,'relabel',jsonb_build_object('candidateId',candidate::text,'ticId',signal_tic::text,
          'axis',axis,'before',old_value,'after',new_value,'source',
          CASE WHEN axis='disposition' THEN (SELECT jsonb_build_object('ruleVersion',rule_version,'appliedAt',applied_at,'sourceRefs',source_refs) FROM candidate_dispositions WHERE candidate_id=candidate)
          ELSE (SELECT jsonb_build_object('executionId',x.id::text,'modelVersion',x.model_version,'thresholdVersion',e.threshold_version) FROM ai_evaluations e JOIN ai_executions x ON x.id=e.execution_id WHERE e.candidate_id=candidate ORDER BY x.started_at DESC,e.id DESC LIMIT 1) END))
        ON CONFLICT(event_key) DO NOTHING RETURNING id INTO event_id;
        IF event_id IS NOT NULL THEN
          INSERT INTO notification_outbox(event_key,user_id,type,payload,preference_epoch,state)
          SELECT cause,u.id,'relabel',jsonb_build_object('ticId',signal_tic::text,'eventId',event_id::text),
            coalesce((s.notification_epochs->>'relabel')::bigint,0),
            CASE WHEN coalesce((s.notification_prefs->>'relabel')::boolean,true) THEN 'pending' ELSE 'excluded' END
          FROM users u LEFT JOIN user_settings s ON s.user_id=u.id WHERE u.status='active'
            AND EXISTS(SELECT 1 FROM submissions m WHERE m.user_id=u.id AND m.matched_candidate_id=candidate
                AND m.match_result IN ('matched','matched_harmonic','duplicate'))
          ON CONFLICT(user_id,event_key) DO NOTHING;
        END IF;
      END IF;
    END LOOP;
    UPDATE notification_signal_state SET disposition=coalesce(next_disposition,disposition),ai_verdict=coalesce(next_ai,ai_verdict)
      WHERE candidate_id=candidate;
END $$;
CREATE FUNCTION notification_signal_trigger() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE candidate BIGINT;
BEGIN
    IF TG_TABLE_NAME='ai_executions' THEN
      FOR candidate IN SELECT candidate_id FROM ai_evaluations WHERE execution_id=NEW.id ORDER BY candidate_id LOOP
        PERFORM notification_signal_changed(candidate);
      END LOOP;
    ELSE PERFORM notification_signal_changed(NEW.candidate_id);
    END IF;
    RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER notification_disposition_changed AFTER INSERT OR UPDATE ON candidate_dispositions
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION notification_signal_trigger();
CREATE CONSTRAINT TRIGGER notification_ai_changed AFTER INSERT OR UPDATE ON ai_evaluations
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION notification_signal_trigger();
CREATE CONSTRAINT TRIGGER notification_ai_execution_changed AFTER INSERT OR UPDATE ON ai_executions
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION notification_signal_trigger();

-- search_path를 고정하고 앱·Gold의 임의 인자 직접 호출을 차단한다.
DO $$ DECLARE fn TEXT; BEGIN
  FOREACH fn IN ARRAY ARRAY['notification_candidate_change()','notification_bundle_published()',
    'notification_signal_changed(bigint)','notification_signal_trigger()'] LOOP
    EXECUTE format('ALTER FUNCTION %s SET search_path = %I, pg_temp',fn,current_schema());
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, planetory_app, planetory_gold_writer',fn);
  END LOOP;
END $$;

DO $$ BEGIN
 EXECUTE format('GRANT UPDATE (payload,source_notification_id,follow_id,follow_epoch,preference_epoch) ON %I.notification_outbox TO planetory_app',current_schema());
END $$;
